apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- hpa.yaml
- istio.yaml
- rollout.yaml
namespace: production
images:
  - name: homeedcomp/argo-combined-app
    newTag: "9e3bd36481f18b20d3ce7b04cb0e19a53ba60c0b"
